package mistureba;

import javax.swing.SwingUtilities;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author laure
 */
public class Intro extends javax.swing.JPanel {
    Janela j;
    Mist m;
    Mistureba lista[];
    Mistureba m1 = new Mistureba();
        
    public void preencheMisturebaP() {
        String[] silabas = {"BOM", "CHA", "RO", "SE", "BA", "BEI", "BOL", "A", "CIA"}; 
        String[] palavras = {"BOMBA", "BOMBACHA", "BASE", "BOLA", "BOMBEIRO", "ROCHA", "BACIA", "BOMBOM", "BOLACHA", "BEISEBOL"}; 
        
        m1.setSilabas(silabas);
        m1.setPalavras(palavras);
        j.jogo.setMistureba(m1);
//        this.lista = new Mistureba[10];
//        this.lista[0] = m1;
    }
    
    
    public void preencheMisturebaI() {
        String[] silabas = {"CK", "TRU", "CLO", "E", "DU", "DAT", "SE", "T", "CA"}; 
        String[] palavras = {"TRUCK", "CLOCK", "TRUE", "DUCK", "DATE", "CLOCK", "SET", "CAT", "ET","DUT"}; 
        m1.setSilabas(silabas);
        m1.setPalavras(palavras);
        j.jogo.setMistureba(m1);
    }
    
    public Intro(Janela j) {
        initComponents();        
        this.j=j;
    }

        
    public void oooo(){
        if(j.jogo instanceof JogoP) {
           preencheMisturebaP();
           j.mistureba.eeeee();
           Labeltext.setText("A partir das \"sílabas\" você deve descobrir quais são as palavras.");
           labelNome.setText("Nome:");
           jButton1.setText("Jogar");
           }
        else if (j.jogo instanceof JogoI){
               preencheMisturebaI();
               j.mistureba.eeeee();
               Labeltext.setText("Using the \"syllables \" you must find out what the words are.");
               labelNome.setText("Name:");
               jButton1.setText("Play");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSpinner1 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        Labeltext = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        nome = new javax.swing.JEditorPane();
        labelNome = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 204));
        jButton1.setText("Jogar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\laure\\Downloads\\tit.png")); // NOI18N

        Labeltext.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Labeltext.setText("A partir das \"sílabas\" você deve descobrir quais são as palavras.");

        nome.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                nomeCaretUpdate(evt);
            }
        });
        nome.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                nomeAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane1.setViewportView(nome);

        labelNome.setFont(new java.awt.Font("Tempus Sans ITC", 1, 24)); // NOI18N
        labelNome.setText("Nome:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelNome, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Labeltext)
                        .addGap(29, 29, 29)))
                .addGap(162, 162, 162)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(57, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Labeltext)
                        .addGap(45, 45, 45)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1))
                .addGap(30, 30, 30)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        j.jogo.setNome(nome.getText());
        j.jogo.setPontuacao(0);
        j.remove(j.introducao);
        j.add(j.mistureba);
        SwingUtilities.updateComponentTreeUI(j);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void nomeCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_nomeCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeCaretUpdate

    private void nomeAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_nomeAncestorAdded
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeAncestorAdded

   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Labeltext;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelNome;
    private javax.swing.JEditorPane nome;
    // End of variables declaration//GEN-END:variables
}
